name: Flask Application Deployment

on: 
  push:
    branches:
      - master
      
jobs:
  build:
    name: Nodejs
    runs-on: ubuntu-20.04
      
    steps:
      - uses: actions/checkout@v2

      - name: rsync Deployment
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: .
          remote_path: ${{ secrets.DEPLOY_API_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
        
      - name: Build Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker container stop $(sudo docker ps | grep -w api-parksamart | awk {'print $1}')
            docker container rm $(sudo docker ps -a | grep -w api-parksamart | awk {'print $1}')
            docker image rm api-parksamart
            docker build -t api-parksamart:latest .
            sudo docker run -d -p 81:5000 api-parksamart:latest
            
