name: Flask Application Testing

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    env:
     IMAGE_NAME: api-parksamart
     IMAGE_TAG: latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker build
      run: docker build -t $IMAGE_NAME:$IMAGE_TAG .
      
    - name: Test
      run: docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG
